### ISSUE TITLE
For RAID add mdadm_udev to HOOKS array in mkinitcpio.conf

### ISSUE THREAD

**Issue by jakefb** [calamares/calamares-manjaro#10]
I used Calamares to install Manjaro on a 16.06-rc1 raid 0 array which I created with mdadm, but when I booted the system the array partition could not be found, so I had to add mdadm_udev to the HOOKS array in mkinitcpio.conf and regenerate the initramfs image.

Would it be posible to make it so if any raid paritions are selected, mdadm_udev is added to the HOOKS array in /etc/mkinitcpio.conf, so they are mounted by fstab at boot?

I created an issue for Thus too https://github.com/manjaro/thus/issues/54

**Comment by hphilm** [comment]
Please open for this an issue at the upstream bugtracker: https://calamares.io/bugs/secure/Dashboard.jspa

**Comment by ahmedcevizci** [comment]
I used to install Manjaro Gnome 16.10 via Calamares on RAID 0. Then I used to follow above procedures described by @jakefb to be able to boot my unbootable RAID 0 system.

Today I tried to install Manjaro Gnome 17.0 and do the same procedures that I used to correct my RAID 0 install. However this time, Calamares didn't even recognize RAID 0 array and incorrectly recognized individual harddisks as separate. 

If this is intentional, please revert back to old installer. Since previously I could correct my installation after Calamares finished. Now I am left with no choice to use Antergos instead.

Thanks in advance.

**Comment by hphilm** [comment]
**partition** module is managed **upstream**. Please open an [issue](https://github.com/calamares/calamares/issues) there. Also it would be good to provide the log output of `sudo -E calamares -d` and a detailed issue description.
